# Unbound configuration file for Debian.
#
# See the unbound.conf(5) man page.
#
# See /usr/share/doc/unbound/examples/unbound.conf for a commented
# reference config file.
#
# The following line includes additional configuration files from the
# /etc/unbound/unbound.conf.d directory.
include: "/etc/unbound/unbound.conf.d/*.conf"

server:
	interface: 127.0.0.1
	# interface: ::1

	access-control: 127.0.0.0/8 allow
	# access-control: ::1 allow

	# To enable logging, a couple of additional steps might be needed.
	# 1. if not already created, create the /var/log/unbound.log file and make sure that it is owned by unbound:unbound
	# 2. you might also need to create an apparmor local override:
	#	echo "/var/log/unbound.log rw," > /etc/apparmor.d/local/usr.sbin.unbound
	#	apparmor_parser -r /etc/apparmor.d/usr.sbin.unbound

	# logfile: /var/log/unbound.log
	# verbosity: 1
	# log-queries: yes
	# log-time-ascii: yes

remote-control:
	# Set up keys and certificates with unbound-control-setup.
	# On Debian this is done automatically by the installer.
	control-enable: yes

	control-interface: 127.0.0.1
	control-port: 8953
