#!/bin/bash

# ------------------------------------------------------------------------------
# Copyright (c) Attila Kovari
# All rights reserved.
#
# MIT License
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
# ------------------------------------------------------------------------------



source ./utils
CONFIGFILE=./postnimda.cf

CURRENT_USER=$(id -u)
CURRENT_USER_NAME=$(id -un ${CURRENT_USER})

virtual_user=$1

DOVECOT_PASSDB_DENY_FILE=""



[[ ${CURRENT_USER} -eq 0 ]] || {
        error "Sorry ${CURRENT_USER_NAME}, but I must be run as root!"
	exit 1
}

[[ -f ${CONFIGFILE} ]] || {
	error "Config file does not exist! Please run setup first."
	exit 1
}

[[ ! -z ${virtual_user} ]] || {
	echo "Usage: $0 <user@domain>"
	exit 1
}

virtual_u=$(echo "${virtual_user}" | cut -f1 -s -d "@")
virtual_d=$(echo "${virtual_user}" | cut -f2 -s -d "@")

[[ ! -z ${virtual_u} && ! -z ${virtual_d} ]] || {
	echo "Usage: $0 <user@domain>"
	exit 1
}



########## Read configuration from file
##########
source ${CONFIGFILE}

sanity_check "${DOVECOT_PASSDB_DENY_FILE}"
[[ $? -eq 0 ]] || {
	error "'DOVECOT_PASSDB_DENY_FILE' is not set or invalid!"
	exit 1
}



########## Unblocking user in Dovecot
##########
info "Unblocking user '${virtual_user}'."

if [[ $(grep -E "^${virtual_user}$" ${DOVECOT_PASSDB_DENY_FILE}) ]]; then
	info "Removing user from block list."

	result=$(grep -v -E "^${virtual_user}$" ${DOVECOT_PASSDB_DENY_FILE})
	echo "${result}" > ${DOVECOT_PASSDB_DENY_FILE}
	info "User was unblocked."
else
	warning "User not blocked in ${DOVECOT_PASSDB_DENY_FILE}. Nothing to remove."
fi

info "Done."
echo



exit 0
