#!/bin/bash

# ------------------------------------------------------------------------------
# Copyright (c) Attila Kovari
# All rights reserved.
#
# MIT License
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
# ------------------------------------------------------------------------------



# check that input is set and starts with a '/'
function sanity_check() {

	# check the extglob status
	shopt -q extglob
	extglob_status=$?

	shopt -s extglob

	# remove all trailing "/"
	input="${1%%+(/)}"

	# restore extglob to its previous state
	if [[ ! ${extglob_status} -eq 0 ]]; then
		shopt -u extglob
	fi

	[[ ! -z ${input} ]] || {
	# value not set
	return 1
	}

	case "${input}" in
		/*) return 0 ;;
		* ) return 1 ;;
	esac
}



# get the user's confirmation
function prompt_yes_no() {
	question="$1"
	if [[ -z ${question} ]]; then
		question="Are you sure you want to continue?"
	fi

	read -p "$question [Y/N]? " yesno
	case ${yesno} in
		[Yy]* ) return 0;;
		[Nn]* ) return 1;;
	esac
}



function continue_check {
	prompt_yes_no "$1"
	[[ ! $? -eq 0 ]] && {
		exit 1
	}

	return 0
}



function info() {
	echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')] INFO: $*"
}

function note() {
	echo -e "[$(date +'%Y-%m-%dT%H:%M:%S%z')]\033[1;32m NOTE: $*\033[0m"
}

function warning() {
	echo -e "[$(date +'%Y-%m-%dT%H:%M:%S%z')]\033[1;33m WARNING: $*\033[0m"
}


# from Google's Shell Style Guide
# https://google.github.io/styleguide/shellguide.html#s3.1-stdout-vs-stderr
function error() {
	echo -e "[$(date +'%Y-%m-%dT%H:%M:%S%z')]\033[1;31m ERROR: $*\033[0m" >&2
}
